import io
import time

import pandas as pd
import plotly.graph_objects as go
from openpyxl import Workbook, load_workbook

import export_core


def test_export_dashboard_html_contains_watermark_and_cards():
    cards = [export_core.CardSummary(name="PV", total=123.0, average=4.5)]
    res = export_core.export_dashboard_html(
        product_name="Prod",
        user_email="a@example.com",
        language_default="zh",
        cards=cards,
        charts=[],
    )
    s = res.content.decode("utf-8")
    assert "Generated by Prod" in s
    assert "a@example.com" in s
    assert "PV" in s
    assert res.sha256


def test_export_dashboard_xlsx_has_expected_sheets_and_image_sheet_optional():
    df = pd.DataFrame({"x": [1, 2, 3], "y": [10.0, 20.0, 30.0]})
    fig = go.Figure(data=[go.Scatter(x=df["x"], y=df["y"])])
    chart = export_core.ChartBundle(title="趋势", figure=fig, table=df)
    cards = [export_core.CardSummary(name="PV", total=123.0, average=4.5)]

    res = export_core.export_dashboard_xlsx(
        product_name="Prod",
        user_email="a@example.com",
        cards=cards,
        charts=[chart],
    )

    wb = load_workbook(io.BytesIO(res.content))
    assert any(s.startswith("Dashboard_") for s in wb.sheetnames)
    assert "Dashboard_Charts" in wb.sheetnames
    ws = wb["Dashboard_Charts"]
    assert ws["A1"].value and "Generated by Prod" in str(ws["A1"].value)
    assert len(getattr(ws, "_images", [])) >= 1


def test_task_manager_runs_and_returns_result():
    mgr = export_core.ExportTaskManager(max_workers=1)
    est = export_core.estimate_export(1, 0, "html")

    def runner(set_progress, is_cancelled):
        set_progress(20)
        set_progress(80)
        data = b"ok"
        return export_core.ExportResult(content=data, sha256=export_core._sha256(data))

    task = mgr.submit(user_email="u@e.com", export_format="html", estimate=est, runner=runner)
    while True:
        t = mgr.get(task.task_id)
        if t and t.status in {"succeeded", "failed", "cancelled"}:
            break
    res = mgr.get_result(task.task_id, user_email="u@e.com")
    assert res is not None
    assert res.content == b"ok"


def test_build_chart_bundles_covers_all_chart_types():
    df = pd.DataFrame(
        {
            "日期": ["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02"],
            "渠道": ["自然", "投放", "自然", "投放"],
            "PV": [10, 20, 30, 40],
            "UV": [3, 5, 7, 9],
            "GMV": [100.0, 200.0, 120.0, 220.0],
        }
    )
    df["日期"] = pd.to_datetime(df["日期"], errors="coerce")

    chart_confs = [
        {"type": "趋势图", "metrics": ["PV", "UV"], "x_axis_mode": "时间列: 日期", "dimension": "不选择", "chart_style": "面积"},
        {"type": "占比图", "metrics": ["PV"], "dimension": "渠道", "x_axis_mode": "--", "chart_style": "环形"},
        {"type": "占比图", "metrics": ["PV"], "dimension": "渠道", "x_axis_mode": "--", "chart_style": "玫瑰"},
        {"type": "排名图", "metrics": ["PV"], "dimension": "渠道", "x_axis_mode": "--", "chart_style": "横向"},
        {"type": "排名图", "metrics": ["PV"], "dimension": "渠道", "x_axis_mode": "--", "chart_style": "竖向"},
        {"type": "漏斗图", "metrics": ["PV", "UV"], "dimension": "不选择", "x_axis_mode": "--"},
        {"type": "漏斗图", "metrics": ["PV"], "dimension": "渠道", "x_axis_mode": "--"},
        {"type": "箱线图", "metrics": ["GMV"], "dimension": "渠道", "x_axis_mode": "--"},
    ]

    bundles = export_core.build_chart_bundles(df, chart_confs)
    assert len(bundles) == len(chart_confs)
    assert all(b.figure is not None for b in bundles)
    assert all(isinstance(b.table, pd.DataFrame) for b in bundles)


def test_estimate_export_returns_nonzero_for_both_formats():
    e_html = export_core.estimate_export(3, 2, "html")
    e_xlsx = export_core.estimate_export(3, 2, "xlsx")
    assert e_html.size_bytes > 0 and e_html.estimate_seconds > 0
    assert e_xlsx.size_bytes > 0 and e_xlsx.estimate_seconds > 0


def test_task_cancel_marks_cancelled():
    mgr = export_core.ExportTaskManager(max_workers=1)
    est = export_core.estimate_export(1, 0, "html")

    def runner(set_progress, is_cancelled):
        for p in range(10, 90, 10):
            if is_cancelled():
                raise RuntimeError("cancelled")
            set_progress(p)
            time.sleep(0.02)
        data = b"never"
        return export_core.ExportResult(content=data, sha256=export_core._sha256(data))

    task = mgr.submit(user_email="u@e.com", export_format="html", estimate=est, runner=runner)
    assert mgr.cancel(task.task_id, user_email="u@e.com") is True
    for _ in range(200):
        t = mgr.get(task.task_id)
        if t and t.status in {"cancelled", "failed", "succeeded"}:
            break
        time.sleep(0.01)
    t = mgr.get(task.task_id)
    assert t is not None
    assert t.status in {"cancelled", "failed"}


def test_format_number_handles_nan_and_units():
    assert export_core.format_number(float("nan")) == "—"
    assert export_core.format_number(10000) == "1.00万"
    assert export_core.format_number(100000000) == "1.00亿"


def test_safe_sheet_title_sanitizes_and_truncates():
    raw = "a/b\\c*?:[d]" + ("x" * 60)
    title = export_core._safe_sheet_title(raw)
    assert len(title) <= 31
    for ch in "\\/*?:[]":
        assert ch not in title


def test_write_df_table_sets_filter_freeze_and_number_format():
    wb = Workbook()
    ws = wb.active
    df = pd.DataFrame({"colA": [1.23456, 2.0], "colB": ["x", "y"]})
    export_core._write_df_table(ws, df, start_row=3, start_col=2)
    assert ws.freeze_panes is not None
    assert ws.auto_filter.ref == "B3:C5"
    assert ws["B4"].number_format == "0.0000"


def test_task_manager_failed_sets_error_and_no_result():
    mgr = export_core.ExportTaskManager(max_workers=1)
    est = export_core.estimate_export(0, 0, "html")

    def runner(set_progress, is_cancelled):
        set_progress(10)
        raise ValueError("boom")

    task = mgr.submit(user_email="u@e.com", export_format="html", estimate=est, runner=runner)
    for _ in range(200):
        t = mgr.get(task.task_id)
        if t and t.status in {"succeeded", "failed", "cancelled"}:
            break
        time.sleep(0.01)
    t = mgr.get(task.task_id)
    assert t is not None
    assert t.status == "failed"
    assert t.error_message and "boom" in t.error_message
    assert mgr.get_result(task.task_id, user_email="u@e.com") is None


def test_task_manager_access_control():
    mgr = export_core.ExportTaskManager(max_workers=1)
    assert mgr.get("not-exist") is None
    assert mgr.cancel("not-exist", user_email="u@e.com") is False
